# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
group=de.cech12.bucketlib
mod_version=5.3.0.1
mod_id=bucketlib
mod_name=BucketLib
mod_author=Cech12
mod_license=The MIT License (MIT)
mod_url=https://github.com/cech12/BucketLib
mod_issue_tracker=https://github.com/cech12/BucketLib/issues
description=A library mod for custom buckets.

# Common
java_version=25
minecraft_version=26.3
minecraft_version_range=[26.3, 27)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.3-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.161.0+26.3
fabric_loader_version=0.19.5
cloth_config_version=26.3.159
mod_menu_version=21.0.0

# Forge, see https://files.minecraftforge.net/net/minecraftforge/forge/ for new versions
# forge_version=54.0.26
# forge_loader_version_range=[54,)

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.3.0.39-beta
neoforge_loader_version_range=[1,)

# test
# test_milk_enabled=false

# jei
jei_version=31.8.0.49
jei_version_range=[31.8.0.49,)

# rei
rei_version=26.3.823
rei_version_range=[26.3.823,)
architectury_version=22.0.3

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
