modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/cech12/BucketLib/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="bucketlib"
    version="${file.jarVersion}"
    displayName="BucketLib"
    displayURL="https://github.com/cech12/BucketLib"
    logoFile="logo.png"
    authors="Cech12"
    description='''
    A library mod for custom buckets.
    '''
[[dependencies.bucketlib]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bucketlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bucketlib]]
   modId="jei"
   mandatory=false
   versionRange="[11.4.0.287,)"
   ordering="NONE"
   side="BOTH"